crEate table Customer (
     id integer PRIMARY KEY,
     cname VARCHAR(225),
     Address VARCHAR(255),
     Gender CHAR(2),
     City VARCHAR(225),
     Pincode INTEGER
     );


INSERT INTO Customer 
VALUES(1251, "Ram Kumar", "Dilbag Nagar", 'M', 'Jalandar', 144002),
      (1300, 'Shayam Singh', 'Ludhiana H.O', 'M', 'Ludhiana', 141001),
      (245, "Neelabh Shukla", "Ashok Nagar", 'M', 'Jalandar', 144003),
      (210, "Barkha Singh", "Dilbag Nagar", 'F', 'Jalandar', 144002),
      (500, 'Shayam Singh', 'Ludhiana H.O', 'M', 'Ludhiana', 141001);


 INSERT INTO worker
    VALUES(10, 'abcdi', 'xyz', 20000, '2014-02-20 09:00:00', 'Admin');

